// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmu5hS6cnj6bXe2Z9M9u47cwUkOGjcAI',
    appId: '1:314516809864:web:290025382e6c13b6d8d73d',
    messagingSenderId: '314516809864',
    projectId: 'refund-class',
    authDomain: 'refund-class.firebaseapp.com',
    storageBucket: 'refund-class.firebasestorage.app',
    measurementId: 'G-W8PHLKQVWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-_PDZbnZHzfHo_Bm6r90CtXcdFlZRnI',
    appId: '1:314516809864:android:b18e10ffdaced42ed8d73d',
    messagingSenderId: '314516809864',
    projectId: 'refund-class',
    storageBucket: 'refund-class.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvyZcpzEWjv-RkQFteQUhD4jCn09Qx8M',
    appId: '1:314516809864:ios:5fc9bf0ba0e23c6bd8d73d',
    messagingSenderId: '314516809864',
    projectId: 'refund-class',
    storageBucket: 'refund-class.firebasestorage.app',
    iosBundleId: 'com.example.refundClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvyZcpzEWjv-RkQFteQUhD4jCn09Qx8M',
    appId: '1:314516809864:ios:5fc9bf0ba0e23c6bd8d73d',
    messagingSenderId: '314516809864',
    projectId: 'refund-class',
    storageBucket: 'refund-class.firebasestorage.app',
    iosBundleId: 'com.example.refundClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzmu5hS6cnj6bXe2Z9M9u47cwUkOGjcAI',
    appId: '1:314516809864:web:decc471c2f90e394d8d73d',
    messagingSenderId: '314516809864',
    projectId: 'refund-class',
    authDomain: 'refund-class.firebaseapp.com',
    storageBucket: 'refund-class.firebasestorage.app',
    measurementId: 'G-YZ18T694JR',
  );
}
